services:
  server:
    build: server
    deploy:
      replicas: 2
  pinger:
    build: pinger
    # command: ["http://server:5000"]  # <-- This works when `deploy: replicas: 2` is commented out.
    command: ["http://${COMPOSE_PROJECT_NAME}-server-1:5000", "http://${COMPOSE_PROJECT_NAME}-server-2:5000"]
