version: "3.8"
services:
  writer:
    build: writer
    volumes:
    - ${VOLUME:-virtual}:/shared
  reader:
    build: reader
    volumes:
    - ${VOLUME:-virtual}:/shared
  server:
    build: server
    volumes:
    - ${VOLUME:-virtual}:/shared
    ports:
    - ${PORT:-5000}:80
volumes:
  virtual: {}
