name: Manually run `step0_sleep`

on:
  workflow_dispatch:

jobs:
  run_step0_sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Run
        run: (cd step0_sleep; docker compose up --build)
