name: Run `step10_indexed_replicas`

on:
  workflow_dispatch:
  push:

jobs:
  run_step10_indexed_replicas:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Run with full output
        run: (cd step10_indexed_replicas; docker compose up --build)
      - name: Run with compact output
        run: (cd step10_indexed_replicas; docker compose up --build 2>&1 | grep HOSTNAME)
      - name: Run with full output N=10
        run: (cd step10_indexed_replicas; N=10 docker compose up --build)
      - name: Run with compact output N=10
        run: (cd step10_indexed_replicas; N=10 docker compose up --build 2>&1 | grep HOSTNAME)
